data:
  covairate_name: ["X", "U"]  
  x_dim: 2
  n_MC: 10000
  data_seed: 17
  X_range: [-1, 1, 51]  
  U_range: [-1, 1, 51]

  alpha: 0.05
  delta: 0.65

sample_settings:
  small_n:
    n_rct: [100, 25, 20]
    n_obs: [5000, 0, 20]
  
  ratio:
    n_rct: [100, 25, 20]
    n_obs: [5000, 1250, 20]

  large_N:
    n_rct: [200, 0, 20]
    n_obs: [1000, 250, 20]


data_gen:
  scenario_1:
    om_A0_par:    # GP parameters for FOM_0
      ls: [1,1]
      alpha: [1,1]
      kernel: "rbf"

    om_A1_par:      # GP parameters for FOM_1
      ls: [0.5, 0.5]
      alpha: [5, 5]
      kernel: "rbf"

    w_sel_par:      # Nested trial participation P(S=1 | X,U) GP parameters
      ls: [1,1000000]
      alpha: [0, 0]
      kernel: "rbf"

    w_trt_par:      # OS treatment assignment P(A=1 | S=2, X,U) GP parameters
      ls: [1000000,1000000]
      alpha: [0, 0]
      kernel: "rbf"

  scenario_2:
    om_A0_par:    # GP parameters for FOM_0
      ls: [1,1]
      alpha: [1,1]
      kernel: "rbf"

    om_A1_par:      # GP parameters for FOM_1
      ls: [0.5, 0.5]
      alpha: [5, 5]
      kernel: "rbf"

    w_sel_par:      # Nested trial participation P(S=1 | X,U) GP parameters
      ls: [1,1000000]
      alpha: [0, 0]
      kernel: "rbf"

    w_trt_par:      # OS treatment assignment P(A=1 | S=2, X,U) GP parameters
      ls: [1000000, 0.5]
      alpha: [0, 0]
      kernel: "rbf"

  scenario_3:
    om_A0_par:    # GP parameters for FOM_0
      ls: [1,1]
      alpha: [1,1]
      kernel: "rbf"

    om_A1_par:      # GP parameters for FOM_1
      ls: [0.5, 0.5]
      alpha: [5, 5]
      kernel: "rbf"

    w_sel_par:      # Nested trial participation P(S=1 | X,U) GP parameters
      ls: [1,1000000]
      alpha: [0, 0]
      kernel: "rbf"

    w_trt_par:      # OS treatment assignment P(A=1 | S=2, X,U) GP parameters
      ls: [1000000, 0.5]
      alpha: [0, 10]
      kernel: "rbf"
  
pasx:
  lb: 0.1
  ub: 0.9
  trial: 0.5


relative_path: 
  "code/rct_data/experiments_n"